// SPDX-License-Identifier: Apache-2.0
/// @file   plugins/links/quic/plugin_entry.cpp
/// @brief  Plugin entry surface generated by `GN_LINK_PLUGIN`
///         (`sdk/cpp/link_plugin.hpp`).

#include "quic.hpp"

#include <sdk/cpp/link_plugin.hpp>

GN_LINK_PLUGIN(::gn::link::quic::QuicLink, "quic")
